// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /depot/cms/private/users/kaur214/analysis_facility/limits/destructive/ZPrimeCombine/./userfuncs/ZPrimeVoigtian.h;
#pragma link C++ defined_in "/depot/cms/private/users/kaur214/analysis_facility/limits/destructive/ZPrimeCombine/./userfuncs/ZPrimeVoigtian.cxx";

#endif
