/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
o *****************************************************************************/

#ifndef ZPRIMEELEBKGPDF5
#define ZPRIMEELEBKGPDF5

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ZPrimeEleBkgPdf5 : public RooAbsPdf {
public:
  ZPrimeEleBkgPdf5() {} ; 
  ZPrimeEleBkgPdf5(const char *name, const char *title,
              RooAbsReal& _mass,
              RooAbsReal& _bkg_a,
              RooAbsReal& _bkg_b,
              RooAbsReal& _bkg_c,
              RooAbsReal& _bkg_d,
              RooAbsReal& _bkg_e,
              RooAbsReal& _bkg_b2,
              RooAbsReal& _bkg_c2,
              RooAbsReal& _bkg_d2,
              RooAbsReal& _bkg_thr,
              RooAbsReal& _bkg_syst_a,
              RooAbsReal& _bkg_syst_b
  );
  ZPrimeEleBkgPdf5(const ZPrimeEleBkgPdf5& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ZPrimeEleBkgPdf5(*this,newname); }
  inline virtual ~ZPrimeEleBkgPdf5() { }

protected:

  RooRealProxy  mass;
  RooRealProxy  bkg_a;
  RooRealProxy  bkg_b;
  RooRealProxy  bkg_c;
  RooRealProxy  bkg_d;
  RooRealProxy  bkg_e;
  RooRealProxy  bkg_b2;
  RooRealProxy  bkg_c2;
  RooRealProxy  bkg_d2;
  RooRealProxy  bkg_thr;
  RooRealProxy  bkg_syst_a;
  RooRealProxy  bkg_syst_b;

  Double_t evaluate() const ;

private:
  ClassDef(ZPrimeEleBkgPdf5,1) // Your description goes here...
};

#endif
